package:
  name: mohex
  version: 2.0

source:
  git_url: https://github.com/cgao3/benzene-vanilla-cmake.git

requirements:
  build:
    - cmake
    - libdb
    - libboost
  
  run: 
    - libboost
    - libstdcxx-ng
    - libgcc-ng

test:
  commands:
    - printf "genmove b\nquit" | mohex
